{{- /*
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if eq .Values.controller.enable true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "controller.fullname" . }}-conf
  labels:
    {{- include "controller.labels" . | nindent 4 }}
data:
{{- include "controller.config" . }}
{{- end }}